name: Deploy to fly.io

on:
  push:
    branches: [ main ]
    
env:
  FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
  SHYNET_PIXEL_SRC: ${{ secrets.SHYNET_PIXEL_SRC }}
  SHYNET_SCRIPT_SRC: ${{ secrets.SHYNET_SCRIPT_SRC }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          
        - name: Setup fly.io CLI
          run: curl -L https://fly.io/install.sh | sh
          
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.1.1        
          with:
            node-version: 16.x

        - name: Build webapp
          run: node build.js
          
        - name: Deploy to fly.io
          run: /home/runner/.fly/bin/flyctl deploy
